name: Update Cached Data

on:
  schedule:
    - cron: "0 14 * * *" # should run after 14:00 Vienna time to get the latest day ahead prices
  workflow_dispatch: # Allow manual trigger if needed

permissions:
  contents: write # Allow writing to the repository
  pages: write # Allow GitHub Pages deployment
  id-token: write # Allow OpenID Connect for GitHub Pages deployment

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run the prefetching script to fetch Austrian and German prices
      - name: Fetch and Update Cached Data
        run: node prefetch.js

      # Copy updated data to backup folder
      - name: Copy Data to Backup Folder
        run: |
          cp page/cached-data-austria.json backup/cached-data-austria.json
          cp page/cached-data-germany.json backup/cached-data-germany.json

      # Commit and push changes to keep workflow active
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add backup/
          git diff --staged --quiet || git commit -m "Update cached data - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push

      # Deploy updated data to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Selected Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./page

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
